# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
tokens:
  - addressOrDenom: "0x7542c62565f48520A34Cf79884656efDEdD38176"
    chainName: arbitrum
    connections:
      - token: ethereum|bsc|0x02CF1778c07584D92b610E0C03fA285DfD00c354
      - token: ethereum|kalychain|0x8A1ABbB167b149F2493C8141091028fD812Da6E4
      - token: ethereum|polygon|0x285C14145EB75A1918B48f93E126139ea1a0f294
    decimals: 18
    name: KalyCoin
    standard: EvmHypSynthetic
    symbol: KLC
    logoURI: "/logos/klc.svg"
  - addressOrDenom: "0x02CF1778c07584D92b610E0C03fA285DfD00c354"
    chainName: bsc
    connections:
      - token: ethereum|arbitrum|0x7542c62565f48520A34Cf79884656efDEdD38176
      - token: ethereum|kalychain|0x8A1ABbB167b149F2493C8141091028fD812Da6E4
      - token: ethereum|polygon|0x285C14145EB75A1918B48f93E126139ea1a0f294
    decimals: 18
    name: KalyCoin
    standard: EvmHypSynthetic
    symbol: KLC
    logoURI: "/logos/klc.svg"
  - addressOrDenom: "0x8A1ABbB167b149F2493C8141091028fD812Da6E4"
    chainName: kalychain
    connections:
      - token: ethereum|arbitrum|0x7542c62565f48520A34Cf79884656efDEdD38176
      - token: ethereum|bsc|0x02CF1778c07584D92b610E0C03fA285DfD00c354
      - token: ethereum|polygon|0x285C14145EB75A1918B48f93E126139ea1a0f294
    decimals: 18
    name: KalyCoin
    standard: EvmHypNative
    symbol: KLC
    logoURI: "/logos/klc.svg"
  - addressOrDenom: "0x285C14145EB75A1918B48f93E126139ea1a0f294"
    chainName: polygon
    connections:
      - token: ethereum|arbitrum|0x7542c62565f48520A34Cf79884656efDEdD38176
      - token: ethereum|bsc|0x02CF1778c07584D92b610E0C03fA285DfD00c354
      - token: ethereum|kalychain|0x8A1ABbB167b149F2493C8141091028fD812Da6E4
    decimals: 18
    name: KalyCoin
    standard: EvmHypSynthetic
    symbol: KLC
    logoURI: "/logos/klc.svg"
  - addressOrDenom: "0x8d0e034611B691683377d2fC9958122a30F7DAab"
    chainName: bsc
    connections:
      - token: ethereum|kalychain|0x0e2318b62a096AC68ad2D7F37592CBf0cA9c4Ddb
    decimals: 18
    name: BNB
    standard: EvmHypNative
    symbol: BNB
    logoURI: "/logos/bnb.svg"
  - addressOrDenom: "0x0e2318b62a096AC68ad2D7F37592CBf0cA9c4Ddb"
    chainName: kalychain
    connections:
      - token: ethereum|bsc|0x8d0e034611B691683377d2fC9958122a30F7DAab
    decimals: 18
    name: BNB
    standard: EvmHypSynthetic
    symbol: BNB
    logoURI: "/logos/bnb.svg"
  - addressOrDenom: "0x1e59F72de6c00c456f7F42708FE8b6b0782E84C6"
    chainName: arbitrum
    collateralAddressOrDenom: "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1"
    connections:
      - token: ethereum|bsc|0x7379A18963039eA1284050b585f422e8156c9eC0
      - token: ethereum|kalychain|0x6E92CAC380F7A7B86f4163fad0df2F277B16Edc6
      - token: ethereum|polygon|0x1E71a8d870F0C491d4fCC965A59493b8B7564949
    decimals: 18
    name: Dai Stablecoin
    standard: EvmHypCollateral
    symbol: DAI
    logoURI: "/logos/dai.svg"
  - addressOrDenom: "0x7379A18963039eA1284050b585f422e8156c9eC0"
    chainName: bsc
    collateralAddressOrDenom: "0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3"
    connections:
      - token: ethereum|arbitrum|0x1e59F72de6c00c456f7F42708FE8b6b0782E84C6
      - token: ethereum|kalychain|0x6E92CAC380F7A7B86f4163fad0df2F277B16Edc6
      - token: ethereum|polygon|0x1E71a8d870F0C491d4fCC965A59493b8B7564949
    decimals: 18
    name: Dai Stablecoin
    standard: EvmHypCollateral
    symbol: DAI
    logoURI: "/logos/dai.svg"
  - addressOrDenom: "0x6E92CAC380F7A7B86f4163fad0df2F277B16Edc6"
    chainName: kalychain
    connections:
      - token: ethereum|arbitrum|0x1e59F72de6c00c456f7F42708FE8b6b0782E84C6
      - token: ethereum|bsc|0x7379A18963039eA1284050b585f422e8156c9eC0
      - token: ethereum|polygon|0x1E71a8d870F0C491d4fCC965A59493b8B7564949
    decimals: 18
    name: Dai Stablecoin
    standard: EvmHypSynthetic
    symbol: DAI
    logoURI: "/logos/dai.svg"
  - addressOrDenom: "0x1E71a8d870F0C491d4fCC965A59493b8B7564949"
    chainName: polygon
    collateralAddressOrDenom: "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063"
    connections:
      - token: ethereum|arbitrum|0x1e59F72de6c00c456f7F42708FE8b6b0782E84C6
      - token: ethereum|bsc|0x7379A18963039eA1284050b585f422e8156c9eC0
      - token: ethereum|kalychain|0x6E92CAC380F7A7B86f4163fad0df2F277B16Edc6
    decimals: 18
    name: Dai Stablecoin
    standard: EvmHypCollateral
    symbol: DAI
    logoURI: "/logos/dai.svg"
  - addressOrDenom: "0x14CFC15Da10d5cfC6A494E183c795067573C7F51"
    chainName: arbitrum
    connections:
      - token: ethereum|bsc|0xF29AD0640731c50d0c7C999D1f8d5Ffb9E2A3da3
      - token: ethereum|kalychain|0xfdbB253753dDE60b11211B169dC872AaE672879b
      - token: ethereum|polygon|0xb974461a9ef2Ff3F408798f551929647ceaB13b4
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ETH
    logoURI: "/logos/eth.svg"
  - addressOrDenom: "0xF29AD0640731c50d0c7C999D1f8d5Ffb9E2A3da3"
    chainName: bsc
    collateralAddressOrDenom: "0x2170Ed0880ac9A755fd29B2688956BD959F933F8"
    connections:
      - token: ethereum|arbitrum|0x14CFC15Da10d5cfC6A494E183c795067573C7F51
      - token: ethereum|kalychain|0xfdbB253753dDE60b11211B169dC872AaE672879b
      - token: ethereum|polygon|0xb974461a9ef2Ff3F408798f551929647ceaB13b4
    decimals: 18
    name: Ether
    standard: EvmHypCollateral
    symbol: ETH
    logoURI: "/logos/eth.svg"
  - addressOrDenom: "0xfdbB253753dDE60b11211B169dC872AaE672879b"
    chainName: kalychain
    connections:
      - token: ethereum|arbitrum|0x14CFC15Da10d5cfC6A494E183c795067573C7F51
      - token: ethereum|bsc|0xF29AD0640731c50d0c7C999D1f8d5Ffb9E2A3da3
      - token: ethereum|polygon|0xb974461a9ef2Ff3F408798f551929647ceaB13b4
    decimals: 18
    name: Ether
    standard: EvmHypSynthetic
    symbol: ETH
    logoURI: "/logos/eth.svg"
  - addressOrDenom: "0xb974461a9ef2Ff3F408798f551929647ceaB13b4"
    chainName: polygon
    collateralAddressOrDenom: "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619"
    connections:
      - token: ethereum|arbitrum|0x14CFC15Da10d5cfC6A494E183c795067573C7F51
      - token: ethereum|bsc|0xF29AD0640731c50d0c7C999D1f8d5Ffb9E2A3da3
      - token: ethereum|kalychain|0xfdbB253753dDE60b11211B169dC872AaE672879b
    decimals: 18
    name: Ether
    standard: EvmHypCollateral
    symbol: ETH
    logoURI: "/logos/eth.svg"
  - addressOrDenom: "0x706C9a63d7c8b7Aaf85DDCca52654645f470E8Ac"
    chainName: kalychain
    connections:
      - token: ethereum|polygon|0x0a6364152EA7a487C697a36Eb2522f48bC62fB4c
    decimals: 18
    name: Polygon Ecosystem Token
    standard: EvmHypSynthetic
    symbol: POL
    logoURI: "/logos/pol.svg"
  - addressOrDenom: "0x0a6364152EA7a487C697a36Eb2522f48bC62fB4c"
    chainName: polygon
    connections:
      - token: ethereum|kalychain|0x706C9a63d7c8b7Aaf85DDCca52654645f470E8Ac
    decimals: 18
    name: Polygon Ecosystem Token
    standard: EvmHypNative
    symbol: POL
    logoURI: "/logos/pol.svg"
  - addressOrDenom: "0xD0a1d1b8E10625eE7Ed4Be4Aa7afA7f169411FBd"
    chainName: arbitrum
    collateralAddressOrDenom: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
    connections:
      - token: ethereum|kalychain|0x9cAb0c396cF0F4325913f2269a0b72BD4d46E3A9
      - token: ethereum|polygon|0xB3dF48224FA257D55e01342592f9A24cefc2628e
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
    logoURI: "/logos/usdc.svg"
  - addressOrDenom: "0x9cAb0c396cF0F4325913f2269a0b72BD4d46E3A9"
    chainName: kalychain
    connections:
      - token: ethereum|arbitrum|0xD0a1d1b8E10625eE7Ed4Be4Aa7afA7f169411FBd
      - token: ethereum|polygon|0xB3dF48224FA257D55e01342592f9A24cefc2628e
    decimals: 6
    name: USD Coin
    standard: EvmHypSynthetic
    symbol: USDC
    logoURI: "/logos/usdc.svg"
  - addressOrDenom: "0xB3dF48224FA257D55e01342592f9A24cefc2628e"
    chainName: polygon
    collateralAddressOrDenom: "0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359"
    connections:
      - token: ethereum|arbitrum|0xD0a1d1b8E10625eE7Ed4Be4Aa7afA7f169411FBd
      - token: ethereum|kalychain|0x9cAb0c396cF0F4325913f2269a0b72BD4d46E3A9
    decimals: 6
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC
    logoURI: "/logos/usdc.svg"
  - addressOrDenom: "0xFDb3307a16442ed5A7C040AE1600a3B3D3C8e7D9"
    chainName: arbitrum
    collateralAddressOrDenom: "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9"
    connections:
      - token: ethereum|kalychain|0x2CA775C77B922A51FcF3097F52bFFdbc0250D99A
      - token: ethereum|polygon|0x2f7c83FC82A0e39A997c262e5BAB13176C275104
    decimals: 6
    name: Tether USD
    standard: EvmHypCollateral
    symbol: USDT
    logoURI: "/logos/usdt.svg"
  - addressOrDenom: "0x2CA775C77B922A51FcF3097F52bFFdbc0250D99A"
    chainName: kalychain
    connections:
      - token: ethereum|arbitrum|0xFDb3307a16442ed5A7C040AE1600a3B3D3C8e7D9
      - token: ethereum|polygon|0x2f7c83FC82A0e39A997c262e5BAB13176C275104
    decimals: 6
    name: Tether USD
    standard: EvmHypSynthetic
    symbol: USDT
    logoURI: "/logos/usdt.svg"
  - addressOrDenom: "0x2f7c83FC82A0e39A997c262e5BAB13176C275104"
    chainName: polygon
    collateralAddressOrDenom: "0xc2132D05D31c914a87C6611C10748AEb04B58e8F"
    connections:
      - token: ethereum|arbitrum|0xFDb3307a16442ed5A7C040AE1600a3B3D3C8e7D9
      - token: ethereum|kalychain|0x2CA775C77B922A51FcF3097F52bFFdbc0250D99A
    decimals: 6
    name: Tether USD
    standard: EvmHypCollateral
    symbol: USDT
    logoURI: "/logos/usdt.svg"
  - addressOrDenom: "0x3CDbaBE5Bf4E6cfE10A2A326E0ad31b2d16398D4"
    chainName: arbitrum
    collateralAddressOrDenom: "0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f"
    connections:
      - token: ethereum|kalychain|0xaA77D4a26d432B82DB07F8a47B7f7F623fd92455
      - token: ethereum|polygon|0xfF00e814A0dCB9a614585c212C78Fdc596d02e47
    decimals: 8
    name: Wrapped BTC
    standard: EvmHypCollateral
    symbol: WBTC
    logoURI: "/logos/wbtc.svg"
  - addressOrDenom: "0xaA77D4a26d432B82DB07F8a47B7f7F623fd92455"
    chainName: kalychain
    connections:
      - token: ethereum|arbitrum|0x3CDbaBE5Bf4E6cfE10A2A326E0ad31b2d16398D4
      - token: ethereum|polygon|0xfF00e814A0dCB9a614585c212C78Fdc596d02e47
    decimals: 8
    name: Wrapped BTC
    standard: EvmHypSynthetic
    symbol: WBTC
    logoURI: "/logos/wbtc.svg"
  - addressOrDenom: "0xfF00e814A0dCB9a614585c212C78Fdc596d02e47"
    chainName: polygon
    collateralAddressOrDenom: "0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6"
    connections:
      - token: ethereum|arbitrum|0x3CDbaBE5Bf4E6cfE10A2A326E0ad31b2d16398D4
      - token: ethereum|kalychain|0xaA77D4a26d432B82DB07F8a47B7f7F623fd92455
    decimals: 8
    name: Wrapped BTC
    logoURI: "/logos/wbtc.svg"
    standard: EvmHypCollateral
    symbol: WBTC
options: {}